name: Publish
on:
  push:
    # branches:
    #   - main

jobs:
  set-version:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.17.0]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node-version}}

      - name: Create code for distribution
        run: |
          yarn
          yarn tsc --project tsconfig.build.json
          yarn semantic-release

      - name: Publish it
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
        run: |
          cd packaged
          npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
          npm publish --ignore-scripts
