name: Push
on: [push, pull_request]

jobs:
  install:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.17.0]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node-version}}

      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('yarn.lock') }}

      - name: Install Dependencies
        run: yarn

  lint:
    needs: [install]
    runs-on: ubuntu-latest
    name: Lint checks
    steps:
      - uses: actions/checkout@v2
      - name: Restore node_modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('yarn.lock') }}
      - name: Lint checks
        run: yarn lint

  type:
    needs: [install]
    runs-on: ubuntu-latest
    name: Typescript checks
    steps:
      - uses: actions/checkout@v2
      - name: Restore node_modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('yarn.lock') }}
      - name: Typescript checks
        run: yarn type

  tests:
    needs: [install]
    runs-on: ubuntu-latest
    name: Jest tests
    steps:
      - uses: actions/checkout@v2
      - name: Restore node_modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('yarn.lock') }}
      - name: Jest tests
        run: yarn test
