name: Push
on: [push]

jobs:
  install:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.17.0]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node-version}}

      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('yarn.lock') }}

      - name: Install Dependencies
        run: yarn

  lint:
    needs: [install]
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - uses: actions/checkout@v2
      - name: Restore node_modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('yarn.lock') }}
      - name: Lint
        run: yarn lint

  test-code-gen:
    needs: [install]
    runs-on: ubuntu-latest
    name: Test code generation
    steps:
      - uses: actions/checkout@v2
      - name: Restore node_modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('yarn.lock') }}
      - name: Test code generation
        run: yarn generate
      - name: Test assets copy
        run: yarn generate:assets

  type:
    needs: [install]
    runs-on: ubuntu-latest
    name: Typescript
    steps:
      - uses: actions/checkout@v2
      - name: Restore node_modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('yarn.lock') }}
      - name: Typescript
        run: yarn type

  prettier:
    needs: [install]
    runs-on: ubuntu-latest
    name: Prettier
    steps:
      - uses: actions/checkout@v2
      - name: Restore node_modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('yarn.lock') }}
      - name: Prettier
        run: yarn prettier:check

  tests:
    needs: [install]
    runs-on: ubuntu-latest
    name: Test Coverage
    steps:
      - uses: actions/checkout@v2
      - name: Restore node_modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('yarn.lock') }}
      - name: Test Coverage
        run: yarn test -w 2 --coverage
